prevent crashing on corrupt pointers
in case of missing data for chunked data, return an error instead
of crashing.

fixes:

```
wasteland/backends/Grenache.js:269

  return acc + el.v

TypeError: Cannot read property 'v' of undefined
  at res.reduce (wasteland/backends/Grenache.js:269:25)
  at Array.reduce (<anonymous>)
  at taskParallel (wasteland/backends/Grenache.js:268:27)
  at async.parallelLimit (wasteland/backends/Grenache.js:185:7)
```